# Generated by Django 5.2.17 on 2026-09-09 19:04

import django.db.models.functions.text
from django.db import migrations, models


def normalize_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    seen = set()
    users = list(User.objects.using(schema_editor.connection.alias).all())
    for user in users:
        normalized = user.email.strip().lower()
        if normalized in seen:
            raise RuntimeError(
                "Case-insensitive duplicate emails exist; resolve them before migrating."
            )
        seen.add(normalized)
    for user in users:
        normalized = user.email.strip().lower()
        if user.email != normalized:
            user.email = normalized
            user.save(using=schema_editor.connection.alias, update_fields=["email"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(normalize_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_user_email_ci",
            ),
        ),
    ]
