# Generated by Django 5.2.17 on 2026-09-09 19:04

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.portfolios.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("athletes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        default=apps.portfolios.models.public_slug,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("story", models.TextField(blank=True, max_length=10000)),
                (
                    "recruiting_status",
                    models.CharField(
                        choices=[
                            ("open", "Open to opportunities"),
                            ("committed", "Committed"),
                            ("not_recruiting", "Not recruiting"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("goals", models.TextField(blank=True, max_length=5000)),
                (
                    "athlete",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to="athletes.athleteprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(max_length=50)),
                ("url", models.URLField(max_length=500)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("portfolio", "platform"),
                        name="unique_portfolio_platform",
                    )
                ],
            },
        ),
    ]
