# Generated by Django 5.2.17 on 2026-09-09 19:04

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleteProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("non_binary", "Non-binary"),
                            ("undisclosed", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_team", models.CharField(blank=True, max_length=150)),
                ("biography", models.TextField(blank=True, max_length=5000)),
                ("profile_photo_url", models.URLField(blank=True, max_length=500)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                (
                    "onboarding_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "onboarding_step",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(3)],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athlete_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
