# Generated by Django 5.2.17 on 2026-09-09 19:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("athletes", "0001_initial"),
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, max_length=3000)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="athletes.athleteprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "id"],
            },
        ),
        migrations.CreateModel(
            name="AthleticResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.CharField(max_length=200)),
                ("metric", models.CharField(max_length=100)),
                ("value", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=30)),
                ("date", models.DateField()),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="athletes.athleteprofile",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sports.sport"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "id"],
            },
        ),
    ]
